from abc import ABC, abstractmethod


class PricingModel(ABC):

    @abstractmethod
    def price_european(self, option) -> float: ...

    @abstractmethod
    def delta_european(self, option) -> float: ...

    @abstractmethod
    def gamma_european(self, option) -> float: ...

    @abstractmethod
    def speed_european(self, option) -> float: ...

    @abstractmethod
    def vega_european(self, option) -> float: ...

    @abstractmethod
    def theta_european(self, option) -> float: ...

    @abstractmethod
    def rho_rate_european(self, option) -> float: ...

    @abstractmethod
    def rho_dividend_yield_european(self, option) -> float: ...

    @abstractmethod
    def price_binary(self, option) -> float: ...

    @abstractmethod
    def delta_binary(self, option) -> float: ...

    @abstractmethod
    def gamma_binary(self, option) -> float: ...

    @abstractmethod
    def speed_binary(self, option) -> float: ...

    @abstractmethod
    def vega_binary(self, option) -> float: ...

    @abstractmethod
    def theta_binary(self, option) -> float: ...

    @abstractmethod
    def rho_rate_binary(self, option) -> float: ...

    @abstractmethod
    def rho_dividend_yield_binary(self, option) -> float: ...